CREATE TABLE answer (id INT AUTO_INCREMENT NOT NULL, parent INT DEFAULT NULL, title LONGTEXT NOT NULL, status SMALLINT DEFAULT 0, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_DADD4A253D8E604F (parent), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, user BIGINT DEFAULT NULL, title VARCHAR(255) NOT NULL, status SMALLINT DEFAULT 0, truecount SMALLINT DEFAULT 1, published DATETIME DEFAULT NULL, source LONGTEXT DEFAULT NULL, difficulty SMALLINT DEFAULT 0, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_B6F7494E8D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE questions_cats (question_id INT NOT NULL, question_cat_id INT NOT NULL, INDEX IDX_DE3D1EC01E27F6BF (question_id), INDEX IDX_DE3D1EC0E1F0864B (question_cat_id), PRIMARY KEY(question_id, question_cat_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE questions_tags (question_id INT NOT NULL, question_tag_id INT NOT NULL, INDEX IDX_721C30741E27F6BF (question_id), INDEX IDX_721C3074BD8F4C19 (question_tag_id), PRIMARY KEY(question_id, question_tag_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE questioncat (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(20) NOT NULL, status SMALLINT DEFAULT 0, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE questiontag (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(20) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quiz (id INT AUTO_INCREMENT NOT NULL, user BIGINT DEFAULT NULL, title VARCHAR(20) NOT NULL, loginrequired SMALLINT DEFAULT 0, roundperday SMALLINT DEFAULT 0, hsnumber SMALLINT DEFAULT 0, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_A412FA928D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quizs_cats (quiz_id INT NOT NULL, quiz_cat_id INT NOT NULL, INDEX IDX_12A57644853CD175 (quiz_id), INDEX IDX_12A57644BE9591A (quiz_cat_id), PRIMARY KEY(quiz_id, quiz_cat_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quizcat (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(20) NOT NULL, status SMALLINT DEFAULT 0, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE quiz_question (id BIGINT AUTO_INCREMENT NOT NULL, quiz_id INT NOT NULL, question_id INT NOT NULL, info VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_6033B00B853CD175 (quiz_id), INDEX IDX_6033B00B1E27F6BF (question_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE user (id BIGINT AUTO_INCREMENT NOT NULL, unid VARCHAR(50) NOT NULL, username VARCHAR(20) NOT NULL, password VARCHAR(20) NOT NULL, reset VARCHAR(128) DEFAULT NULL, email VARCHAR(64) NOT NULL, phone VARCHAR(20) DEFAULT NULL, status SMALLINT DEFAULT 0, fname VARCHAR(20) DEFAULT NULL, lname VARCHAR(20) DEFAULT NULL, tel1 VARCHAR(20) DEFAULT NULL, tel2 VARCHAR(20) DEFAULT NULL, tel3 VARCHAR(20) DEFAULT NULL, sex SMALLINT DEFAULT NULL, dborn DATETIME DEFAULT NULL, about LONGTEXT DEFAULT NULL, avatar VARCHAR(50) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, lastact DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649C10C1C37 (unid), UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE users_roles (user_id BIGINT NOT NULL, user_role_id BIGINT NOT NULL, INDEX IDX_51498A8EA76ED395 (user_id), INDEX IDX_51498A8E8E0E3CA6 (user_role_id), PRIMARY KEY(user_id, user_role_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE userrole (id BIGINT AUTO_INCREMENT NOT NULL, role VARCHAR(20) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE answer ADD CONSTRAINT FK_DADD4A253D8E604F FOREIGN KEY (parent) REFERENCES question (id);
ALTER TABLE question ADD CONSTRAINT FK_B6F7494E8D93D649 FOREIGN KEY (user) REFERENCES user (id);
ALTER TABLE questions_cats ADD CONSTRAINT FK_DE3D1EC01E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE;
ALTER TABLE questions_cats ADD CONSTRAINT FK_DE3D1EC0E1F0864B FOREIGN KEY (question_cat_id) REFERENCES questioncat (id) ON DELETE CASCADE;
ALTER TABLE questions_tags ADD CONSTRAINT FK_721C30741E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE;
ALTER TABLE questions_tags ADD CONSTRAINT FK_721C3074BD8F4C19 FOREIGN KEY (question_tag_id) REFERENCES questiontag (id) ON DELETE CASCADE;
ALTER TABLE quiz ADD CONSTRAINT FK_A412FA928D93D649 FOREIGN KEY (user) REFERENCES user (id);
ALTER TABLE quizs_cats ADD CONSTRAINT FK_12A57644853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE;
ALTER TABLE quizs_cats ADD CONSTRAINT FK_12A57644BE9591A FOREIGN KEY (quiz_cat_id) REFERENCES quizcat (id) ON DELETE CASCADE;
ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id);
ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B1E27F6BF FOREIGN KEY (question_id) REFERENCES question (id);
ALTER TABLE users_roles ADD CONSTRAINT FK_51498A8EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE users_roles ADD CONSTRAINT FK_51498A8E8E0E3CA6 FOREIGN KEY (user_role_id) REFERENCES userrole (id) ON DELETE CASCADE;

ALTER TABLE question ADD statuscheck SMALLINT DEFAULT 0;
ALTER TABLE quiz CHANGE hsnumber hsnumber SMALLINT DEFAULT 10;

ALTER TABLE question ADD avatar VARCHAR(50) DEFAULT NULL;


ALTER TABLE quiz ADD qrandom SMALLINT DEFAULT 0, ADD qrepeat SMALLINT DEFAULT 0, DROP random, DROP `repeat`;








ALTER TABLE question ADD avatar VARCHAR(50) DEFAULT NULL, ADD statuscheck SMALLINT DEFAULT 0;
ALTER TABLE questioncat ADD quizcat INT DEFAULT NULL, CHANGE status status SMALLINT DEFAULT 1;
ALTER TABLE questioncat ADD CONSTRAINT FK_E63870277D2357ED FOREIGN KEY (quizcat) REFERENCES quizcat (id);
CREATE UNIQUE INDEX UNIQ_E63870277D2357ED ON questioncat (quizcat);
ALTER TABLE questiontag ADD status SMALLINT DEFAULT 1;
ALTER TABLE quiz ADD analysis SMALLINT DEFAULT 1, ADD reward SMALLINT DEFAULT 0, ADD sharehs SMALLINT DEFAULT 0, ADD shareanalysis SMALLINT DEFAULT 0, ADD sharereward SMALLINT DEFAULT 0, ADD joker5050 SMALLINT DEFAULT 0, ADD jokerpause SMALLINT DEFAULT 0, ADD jokerskip SMALLINT DEFAULT 0, ADD difficulty SMALLINT DEFAULT 0, ADD timelimit SMALLINT DEFAULT 15, ADD qrandom SMALLINT DEFAULT 0, ADD qrepeat SMALLINT DEFAULT 0, ADD trueanswer SMALLINT DEFAULT 0, CHANGE hsnumber hsnumber SMALLINT DEFAULT 10;
ALTER TABLE quizcat ADD questioncat INT DEFAULT NULL;
ALTER TABLE quizcat ADD CONSTRAINT FK_7D2357EDE6387027 FOREIGN KEY (questioncat) REFERENCES questioncat (id);
CREATE UNIQUE INDEX UNIQ_7D2357EDE6387027 ON quizcat (questioncat);
ALTER TABLE userrole ADD status SMALLINT DEFAULT 1;



--22.11.2016, astoian
ALTER TABLE quiz CHANGE hsnumber hsnumber SMALLINT DEFAULT 30, CHANGE joker5050 joker5050 SMALLINT DEFAULT 1, CHANGE jokerpause jokerpause SMALLINT DEFAULT 1, CHANGE jokerskip jokerskip SMALLINT DEFAULT 1, CHANGE qrandom qrandom SMALLINT DEFAULT 1;

--28.11.2016, astoian
ALTER TABLE question CHANGE difficulty difficulty SMALLINT DEFAULT 1;