<?php
// src/AppBundle/Repository/QuestionTagRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTagRepository extends EntityRepository
{
	public function getQuestionTagsAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb->getQuery ()->getResult ();
	}
	
	public function getQuestionTagsAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb;
	}
	
	public function getQuestionTagByTag($title=null) {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->where ( 'lower(e.title) = :title' )
		->setParameter ( 'title', $title )
		;
	
		return $qb->getQuery ()->getOneOrNullResult();
	}
}