<?php
// src/AppBundle/Repository/QuestionTagRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTagRepository extends EntityRepository
{
   
}