<?php
// src/AppBundle/Repository/QuestionCatRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCatRepository extends EntityRepository
{
	public function getQuestionCatsAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb->getQuery ()->getResult ();
	}
	
	public function getQuestionCatsAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb;
	}
	
	public function getQuestionCatByCat($title=null) {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->where ( 'lower(e.title) = :title' )
		->setParameter ( 'title', $title )
		;
	
		return $qb->getQuery ()->getOneOrNullResult();
	}
}