<?php
// src/AppBundle/Repository/QuestionCatRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCatRepository extends EntityRepository
{
   
}