<?php
// src/AppBundle/Repository/QuizCatRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuizCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizCatRepository extends EntityRepository
{
	public function getQuizCatsAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb->getQuery ()->getResult ();
	}
	
	public function getQuizCatsAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb;
	}
	
	public function getQuizCatByCat($title=null) {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->where ( 'lower(e.title) = :title' )
		->setParameter ( 'title', $title )
		;
	
		return $qb->getQuery ()->getOneOrNullResult();
	}
}